version: 2

sources:
  - name: ecom
    schema: jaffle_shop
    description: E-commerce data for the Jaffle Shop
    tables:
      - name: stg_customers
      - name: stg_orders
      - name: stg_order_items
      - name: stg_locations
      - name: stg_products
      - name: stg_supplies
